### ISSUE TITLE
Incorrect behavior when numerous classes added at same time

### ISSUE THREAD

**Issue by romantymoshyk** [timo-reymann/composer-dump-autoload-phpstorm-plugin#1]
Same time include of numerous count of php classes into project causing running numerous instances of command dump-autoload(for each file), this lead to system overload. For example you have added 530 files onetime and plugin will create 530 dump-autoload command instances.
Expected to have only one instance of command onetime

**Comment by timo-reymann** [comment]
Thank you @romantymoshyk for the report of this behaviour. 
I am gonna make a project to reproduce it and add some kind of debounce/queuing to prevent PHPStorm from executing that much system load.

**Comment by timo-reymann** [comment]
Hello @romantymoshyk,

i found a quick and performant way as stated in the commit: https://github.com/timo-reymann/composer-dump-autoload-phpstorm-plugin/commit/232023583e5fe285998c6dc6f9277da2baaaf734 - This should fix your problems

Its in version 1.1.0 to the marketplace (currently in approval), its currently awaiting approval from JetBrains, could you please give me quick feedback once its live? :)

**Comment by romantymoshyk** [comment]
Sure, thank you @timo-reymann !

**Comment by timo-reymann** [comment]
@romantymoshyk  The new version is out, could you give it a try? :)

**Comment by romantymoshyk** [comment]
@timo-reymann, it works amazing, thank you!
