### ISSUE TITLE
Add possibility to configure optimization level

### ISSUE THREAD

**Issue by namikk** [timo-reymann/composer-dump-autoload-phpstorm-plugin#14]
### Description

As there are several types of composer optimizations available, it would be great if there was a way to specify which one we want. For example, I'd like to configure the plugin to execute `composer --optimize-autoloader --apcu-autoloader` or just `composer --apcu-autoloader` instead of the currently hardcoded `composer --optimize-autoloader --apcu-autoloader`.

I haven't found a way to do that at the moment, so I've opened this feature request.

### References

Something like a simple plugin settings entry with a single input field where we specify our own composer parameters would suffice.
Adding a simple ui for the plugin is fairly straightforward (I've done it before): https://plugins.jetbrains.com/docs/intellij/settings-guide.html?from=jetbrains.org#declaring-project-settings
You basically define a <projectConfigurable> in your `plugin.xml` and provide a simple UI definition with a .form file (think there's a UI designer available out of the box, can't remember).

**Comment by timo-reymann** [comment]
Hi @namikk,

thanks for using the plugin and your feature request. I see this would be a very nice additional feature and make it more helpful!
I already implemented configuration for other IntelliJ Plugins and its pretty straightforward.

Stay tuned. It will be released soon! ;) I will keep you up to date in this issue.

Cheers, Timo

**Comment by timo-reymann** [comment]
The new option will be located in `Language & Frameworks > PHP > Composer Dump-Autoload`, directly under the regular composer setttings :rocket: 
![image](https://user-images.githubusercontent.com/21024948/148652318-bf364812-cacd-424e-9f4d-ae10a47c376d.png)

**Comment by timo-reymann** [comment]
Will be shipped with 2.1.0
